name: Thin Evaluation - 24 hours, 5 trials
on: workflow_dispatch
jobs:
  evaluate:
    uses: jon-bell/BeDivFuzz/.github/workflows/evaluation-workflow.yml@ci-23
    with:
      duration: 24h
      trials: 5
      fuzzer_to_invoke: ./bin/jqf-bediv
      java_home: /usr/lib/jvm/java-11-openjdk-amd64/
      report_on_branches: eval-ci, main, ci-23, save-invalid
      runs_on: self-hosted
      PROFILE_HEAP: false
    secrets:
      INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
